# Generated by Django 4.0 on 2022-01-09 15:26

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=core.models.album_image_file_path)),
                ('description', models.TextField()),
                ('artists', models.ManyToManyField(to='core.Artist')),
                ('genders', models.ManyToManyField(to='core.Gender')),
                ('songs', models.ManyToManyField(to='core.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
